### ISSUE TITLE
Manually trigger loading (displaying loading indicator and calling infinite scroll handler)

### ISSUE THREAD

**Issue by pankkor** [pronebird/UIScrollView-InfiniteScroll#12]
On initial loading data for a scrollView I want to display the same loading indicator. So without user interaction I want loading indicator to appear in scroll view and infinite scroll handler to be called.
As far as I can see it's not possible in current implementation. I think this functionality could be useful.

**Comment by pronebird** [comment]
Personally I use separate and more informative loader for that but It should be easy to add a method to manually kick off the infinite scroll loader.



—
Cheers,
Andrej

**Comment by pronebird** [comment]
Stumbled upon couple of issues implementing this (commit 93823dade57137dcf26957532f77ca3bb1c63c9f)

1. Scroll to bottom does not work properly when using self-sizing cells. Content size changes as we scroll (programmatically), so target scroll position is always wrong. Not sure if this can be fixed at all.

2. Loading data into blank tableview leaves content offset at the bottom of content area after content inset removed. We should scroll to top instead. I think that can be safely addressed.

**Comment by facundomr** [comment]
So, there is still no way to do this? I need to show loading indicator until the first set of data is retrieved.

Tnx,

**Comment by pronebird** [comment]
@facundomr sorry for late response. I'll revisit this issue when I have time, maybe there is a way :)

**Comment by jeffmax** [comment]
I am looking for the same functionality to keep a consistent "data loading" experience. Otherwise this looks great- simple and does exactly what I need.

**Comment by cerupcat** [comment]
Has there been any progress to this? SVInfiniteScrolling has this ability but hasn't been updated in a long time and therefore has other issues.

**Comment by Fenil15** [comment]
Any update on this?

**Comment by mikengyn** [comment]
this would be nice

**Comment by staticdreams** [comment]
I guess I need that too ..

**Comment by pronebird** [comment]
I am working on PR for this, commit from last year is out of date:

https://github.com/pronebird/UIScrollView-InfiniteScroll/commit/516825407e110fbd7adf21eee4b97f614817e6f0

There are two issues currently:

1. UINavigationController and UITabBarController modify content inset during first layout pass. Therefore if we call handler manually from viewDidLoad then final content offset is not right. I feel like we have to synchronize it before we finish infinite scroll.

2. Still no luck with self-sizing cells and scroll to bottom.

**Comment by pronebird** [comment]
I pushed few more commits to https://github.com/pronebird/UIScrollView-InfiniteScroll/tree/feature/begin-infinite-scroll

Changes:

- Added new method to start infinite scroll programmatically using `beginInfiniteScroll(forceScroll)`. When `forceScroll = true` scroll view scrolls down to reveal indicator view.
- After loading initial data scroll view returns user back to top.
- `beginInfiniteScroll` won't scroll down during user interaction with scroll view, but will silently fire handler block.
- Added infinite scroll interactions on empty scroll views.
- Improved scroll to bottom which should work fine for self-sizing cells in UITableViews.

Known issues:

- iOS simulator 10.2 from Version 8.2 beta (8C23) has some issues with content offset, but everything works fine on earlier simulators or device with latest iOS 10.

Can anyone give it a try and see if it works or report any issues back?

**Comment by pronebird** [comment]
Released with 1.0.0.
