### ISSUE TITLE
Using [weak self] in Swift closure results crash when popping from UINavigationController.

### ISSUE THREAD

**Issue by gbmksquare** [pronebird/UIScrollView-InfiniteScroll#16]
I reproduced the crash here:

[https://github.com/gbmksquare/InfiniteScrollCrash-Sample](https://github.com/gbmksquare/InfiniteScrollCrash-Sample)

I have the infinite scroll view in a navigation stack. I set up with the code below.

```Swift
tableView.addInfiniteScrollWithHandler { [weak self] (_) -> Void in
    let delay = dispatch_time(DISPATCH_TIME_NOW, Int64(1 * Double(NSEC_PER_SEC)))
        dispatch_after(delay, dispatch_get_main_queue(), { () -> Void in
        self?.tableView.finishInfiniteScroll()
    })
}
```

And I have a UIScrollViewDelegate method implemented.

```Swift
func scrollViewDidScroll(scrollView: UIScrollView) {
    // Some code
}
```

When I activate the infinite scrolling and pop the view, the app crashes at `- (void)pb_setContentOffset:(CGPoint)contentOffset;`

I think it is caused by view controller not retained when it is popping from the navigation stack, and found two workarounds.

```Swift
override func viewWillDisappear(animated: Bool) {
    tableView.finishInfiniteScroll()
    super.viewWillDisappear(animated)
}
// or
override func viewDidDisappear(animated: Bool) {
    tableView.delegate = nil
    super.viewDidDisappear(animated)
}
```

But I have no idea how I can fix it from the library level.

**Comment by pronebird** [comment]
Oh wow, thanks for reporting that! 

Yeah it seems that tableView is still alive while your controller is probably dead at that point.

The crash is in fact happens in the chain of insane events during dealloc

<img width="453" alt="screenshot 2015-08-19 09 47 39" src="https://cloud.githubusercontent.com/assets/704044/9351155/5bf625a4-4657-11e5-91f7-0f3906cfec09.png">

**Comment by gbmksquare** [comment]
Guess I should use workaround for the time being?

**Comment by pronebird** [comment]
Yeah for the time being you can simply reset delegate in your `deinit` method and that should fix the crash.

```swift
deinit {
  self.tableView.delegate = nil
}
```

Btw, testing on iOS 9.0 – no crash.

I believe there is a retain cycle somewhere inside of category.

**Comment by gbmksquare** [comment]
Thanks!

I think I heard somewhere that iOS 9 UIKit uses ARC. Maybe that's why...

**Comment by pronebird** [comment]
I put a simple log into `deinit` of detail controller:

```swift
deinit {
  print("tableView.deinit, tableView.delegate = \(self.tableView.delegate)")
}
```

iOS 9.0 beta 5:
> tableView.deinit, tableView.delegate = nil

iOS 8.4:

> tableView.deinit, tableView.delegate = Optional(<InfiniteScrollCrash_Sample.DetailTableViewController: 0x7d987fa0>)

I was able to reproduce the same crash without InfiniteScroll category on a standard UITableView.

You can pull a sample project:

https://github.com/pronebird/InfiniteScrollCrash-Sample/tree/uikit-crash

go to the same detail controller, scroll table view quickly and hit "Back". 

<img width="453" alt="screenshot 2015-08-19 09 47 39" src="https://cloud.githubusercontent.com/assets/704044/9353549/79e5d3ea-4669-11e5-8279-c3f51a45557e.png">

**Comment by pronebird** [comment]
I prepared two test projects. I can reproduce crash on both of them on iOS 8, iOS 9 seems to work. The key was to set the contentInset to something custom.

1. Obj-C: https://github.com/pronebird/UIkitBugScrollView
2. Swift:  https://github.com/pronebird/UIkitBugScrollViewSwift

**Comment by gbmksquare** [comment]
Wow thanks.

**Comment by pronebird** [comment]
I suppose it is SDK bug. Meanwhile you can manually reset `delegate` on `deinit` without any side-effects in future.

**Comment by allaire** [comment]
Just a heads up @pronebird, I'm getting this crash with iOS 10.0.0 using latest `UIScrollView-InfiniteScroll` version:

![2016-08-29 at 08 41](https://cloud.githubusercontent.com/assets/304461/18051755/6dba3344-6dc4-11e6-9532-09aa81007de6.png)

**Comment by pronebird** [comment]
@allaire I don't think those are related. I can't reproduce that on iOS 10 beta 8 and delegate is correctly set to nil in dealloc
