### ISSUE TITLE
#import "UIScrollView+InfiniteScroll.h" cannot be found in Bridging header when using cocoapods

### ISSUE THREAD

**Issue by DesmondPang** [pronebird/UIScrollView-InfiniteScroll#18]
#import "UIScrollView+InfiniteScroll.h" cannot be found in Bridging header when using Cocoapods. How to solve it? If I don't use Cocoapods and install it manually, it is fine.

**Comment by pronebird** [comment]
Hi,

Do you use frameworks? If so, you can use `@import UIScrollView_InfiniteScroll` I guess

**Comment by DesmondPang** [comment]
No, I use Cocoapods. But if use framework, #import "UIScrollView+InfiniteScroll.h" is no problem.

**Comment by pronebird** [comment]
Alright, then, try using a full include with angled brackets, e.g.:

```
#import <UIScrollView_InfiniteScroll/UIScrollView+InfiniteScroll.h>
````

Xcode should give you a hint.

**Comment by DesmondPang** [comment]
Good. Solved it !! Thank you so much.

**Comment by pronebird** [comment]
You're welcome! :+1:
