### ISSUE TITLE
Infinite Scroll not triggered with small number of items

### ISSUE THREAD

**Issue by TheGeekPharaoh** [pronebird/UIScrollView-InfiniteScroll#2]
We're using your control to pull data down from a web service using a date range and display them in a UICollectionView.  We've noticed that if we only have a small number of items (small enough that they all fit on the screen with no need to scroll) scrolling down to the bottom of the page does not trigger an infinite scroll event the way it would if we had a large number of items.  The event is never started, so our infinite scroll handler block is not called to grab the next set of items in the next date range.

Any idea how we can go about fixing this?  Ideally, if the scroll bounces to the bottom of the scroll view we'd like to have the infinite scroll handler kicked off.

**Comment by pronebird** [comment]
This has been re-fixed once again and now it works smoother.
