### ISSUE TITLE
Keeping the offset when new data arrives

### ISSUE THREAD

**Issue by ldantona** [pronebird/UIScrollView-InfiniteScroll#20]
Hi,

this library is great!

Just one note: is it possible for the table not to scroll up once new data has been loaded?
Scrolling back to the last previously visible cell looks like there are no more data/cells underneath! :(
I'd really like that the offset wouldn't change and the activity indicator replaced with the next cell just loaded.

Many thanks,
DAN

**Comment by pronebird** [comment]
Hi,

Thanks! Do you see that behavior on collection views or table views?

**Comment by ldantona** [comment]
Table view, I'm reloading the table after finishInfiniteScroll, is that correct?
```objective-c
[self.tableView finishInfiniteScroll];
[self.tableView reloadData];
```

**Comment by pronebird** [comment]
Try it the other way around.

```objc
[self.tableView reloadData];
[self.tableView finishInfiniteScroll];
```

Because new data is not yet in table view, infinite scroll thinks there is no new data so it scrolls back to the last cell.

**Comment by ldantona** [comment]
That worked like a charm, thank you!
One last think, off topic but I don't want to bother you with another issue: have you ever experienced the activity indicator not being animated the first time it is shown? It only happens the first time I scroll "more", afterward it's correctly animated.
I've created a custom activity indicator which implements the startRunning ad stopRunning methods and startRunning is called when it's created and never stopped. Could it be a UI refresh issue?

**Comment by pronebird** [comment]
Sounds strange to me. InfiniteScroll should call start/stop automatically for you. That's something I see properly working in demo app. The demo app uses custom indicator too and it works fine, take a look at the implementation of it, maybe it will give you a clue in regard of your custom indicator.

https://github.com/pronebird/UIScrollView-InfiniteScroll/blob/master/InfiniteScrollViewDemo/CustomInfiniteIndicator.m

**Comment by ldantona** [comment]
Ok thank you, I'll give it a look!
