### ISSUE TITLE
Prevent the screen from pushing up after loading

### ISSUE THREAD

**Issue by jamesdo** [pronebird/UIScrollView-InfiniteScroll#21]
It would be nice, if the loaded content wasn't pushed back down after completed loading. There is about 40 pt's where it could be left in place to illustrate to the user that the load was successful, at this point the content is pushed down below the bounds of the screen and the user doesn't necessarily know whether or not the content was loaded.

**Comment by pronebird** [comment]
Possibly related to #20 ?

**Comment by pronebird** [comment]
Please re-open this issue if you still experience the problem that you described.
