### ISSUE TITLE
addInfiniteScrollWithHandler never returns! xcode 7 ios 8.4 simulator

### ISSUE THREAD

**Issue by kalitas** [pronebird/UIScrollView-InfiniteScroll#22]
[self.productsCollectionView addInfiniteScrollWithHandler:^(UICollectionView* collectionView) {
                        
            PFQuery *queryProducts = [PFQuery queryWithClassName:@"products"];
            [queryProducts whereKey:@"objectId" containedIn:[aProvider objectForKey:@"products"]];
            [queryProducts whereKey:@"market" equalTo:self.market];
            [queryProducts setLimit:100];
            [queryProducts setSkip:_skip];
            [queryProducts findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error)
             {                 
                 dispatch_async(dispatch_get_global_queue( DISPATCH_QUEUE_PRIORITY_LOW, 0), ^{
                     dispatch_async(dispatch_get_main_queue(), ^{
                         [MBProgressHUD hideHUDForView:self.view animated:YES];
                         [self.productsCollectionView setAlpha:1.0];
                         [self.searchBar setHidden:NO];
                     });
                 });
                 
                 if (!error)
                 {
                     _skip += 100;
                     
                     NSMutableArray *indexPaths = [NSMutableArray new];
                     NSInteger index = weakSelf.productsOfProviderArray.count;
                     
                     // create index paths for affected items
                     for(PFObject *product in objects) {
                         NSIndexPath *indexPath = [NSIndexPath indexPathForItem:index++ inSection:0];
                         
                         [weakSelf.productsOfProviderArray addObject:product];
                         [indexPaths addObject:indexPath];
                     }
                     
                     // Update collection view
                     [collectionView performBatchUpdates:^{
                         // add new items into collection
                         [collectionView insertItemsAtIndexPaths:indexPaths];
                     } completion:^(BOOL finished) {
                         // finish infinite scroll animations
                         [collectionView finishInfiniteScroll];
                     }];
                     //self.productsOfProviderArray = [self sortProductsArrayAlphabetically:objects];
                     //[self.productsCollectionView reloadData];
                 }
             }];
        }];

here is the collection object (just to show its not null):
po self.productsCollectionView
<UICollectionView: 0x7b27ea00; frame = (0 257; 320 311); clipsToBounds = YES; alpha = 0; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x795ebc60>; layer = <CALayer: 0x795eb010>; contentOffset: {0, 0}; contentSize: {320, 10}> collection view layout: <UICollectionViewFlowLayout: 0x795ebe30>

**Comment by pronebird** [comment]
What do you mean never returns?

**Comment by kalitas** [comment]
Hi pronbird, it means that the code after this line:
[self.productsCollectionView addInfiniteScrollWithHandler:^(UICollectionView* collectionView) {
is not being read by the program...
i mean this this code is not being used:
PFQuery *queryProducts = [PFQuery queryWithClassName:@"products"];
        [queryProducts whereKey:@"objectId" containedIn:[aProvider objectForKey:@"products"]];
        [queryProducts whereKey:@"market" equalTo:self.market];
        [queryProducts setLimit:100];
        [queryProducts setSkip:_skip];
        [queryProducts findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error)
         {                 
             dispatch_async(dispatch_get_global_queue( DISPATCH_QUEUE_PRIORITY_LOW, 0), ^{
                 dispatch_async(dispatch_get_main_queue(), ^{
                     [MBProgressHUD hideHUDForView:self.view animated:YES];
                     [self.productsCollectionView setAlpha:1.0];
                     [self.searchBar setHidden:NO];
                 });
             });

             if (!error)
             {
                 _skip += 100;

                 NSMutableArray *indexPaths = [NSMutableArray new];
                 NSInteger index = weakSelf.productsOfProviderArray.count;

                 // create index paths for affected items
                 for(PFObject *product in objects) {
                     NSIndexPath *indexPath = [NSIndexPath indexPathForItem:index++ inSection:0];

                     [weakSelf.productsOfProviderArray addObject:product];
                     [indexPaths addObject:indexPath];
                 }

                 // Update collection view
                 [collectionView performBatchUpdates:^{
                     // add new items into collection
                     [collectionView insertItemsAtIndexPaths:indexPaths];
                 } completion:^(BOOL finished) {
                     // finish infinite scroll animations
                     [collectionView finishInfiniteScroll];
                 }];
                 //self.productsOfProviderArray = [self sortProductsArrayAlphabetically:objects];
                 //[self.productsCollectionView reloadData];
             }
         }];

**Comment by pronebird** [comment]
The block you provide is executed when user scrolls  to the bottom of the view. It won't be automatically called on first run.

**Comment by ApposingLtd** [comment]
Any progress on this issue? I have recently tried to use your Infinite Scroller on an App I'm currently developing. I have a tableView with a horizontal collectionView within each tableView cell. I need the collectionView's to include infinite scrolling, however whenever the infinite scrolling should be getting called, it never runs the code. For example, within my cellForRowAtIndexPath method I have the following:

            __weak typeof(cell) weakCell = cell;
            [cell.collectionView addInfiniteScrollWithHandler:^(UICollectionView* collectionView) {
                ... code not being reached ...
            }];

Any help with this issue would be greatly appreciated.

Many thanks
Andrew
