### ISSUE TITLE
Scroll to Top Not Working with Infinite Scroll

### ISSUE THREAD

**Issue by wlzch** [pronebird/UIScrollView-InfiniteScroll#32]
I have a UIViewController with tableView which has headerView in it. I am trying to implement a scroll to top functionality if tab bar is tapped. This is how I implement the scrollToTop functionality:

``` php
tableView.scrollRectToVisible(CGRectMake(0, 0, 1, 1), animated: true)
```

But somehow, it only scrolls halfway. The more I call infinite scroll, the farther it gets from the top. I suspect that it sets contentSize with the wrong value. I also tried setContentOffset but it was not working as well.

**Comment by pronebird** [comment]
Hi,

I am not able to reproduce this on demo app. Both `scrollToRowAtIndexPath` and `scrollRectToVisible` work fine. Is it possible that you make a test project to reproduce the issue?

Cheers,
Andrej

**Comment by wlzch** [comment]
Hi,

Thanks for the reply. I haven't been able to make it work yet. Will send you a test project with the issue.

**Comment by fatihyildizhan** [comment]
Just a reminder, don't forget to disable all of scrollviews `scrollsToTop = false` except tableview.

**Comment by pronebird** [comment]
@fatihyildizhan `scrollsToTop` only controls the tap gesture on status bar, so it shouldn't matter if programmatic way of scrolling is being used.

**Comment by pronebird** [comment]
@wlzch any update on this? Did you manage to solve the problem?

**Comment by denly93** [comment]
Hi @pronebird , please try this on infiniteScrollViewDemoSwift commit https://github.com/denly93/UIScrollView-InfiniteScroll/commit/dbf1ef4ac4a2552b66a4feeffc61b1e551179c44

Eventhough without implementing headerview inside the tableview, scroll to top also not working properly.
The bug only occurs at the first time, please scroll down until new items show up, and then click tabbar on the left side, tableview will not scroll up properly

**Comment by pronebird** [comment]
Hi @denly93,

thanks for reproducing this.

It works fine with fixed height cells, but fails on self-sizing cells. Tap on status bar works fine though. Category code is not really doing anything when scrolling happens programmatically. Therefore I think there is something going on in table view guts. I mark it as UIKit bug until proven otherwise.

As a workaround for tables with self-sizing cells, I can suggest to use row-based scrolling which was fixed to function properly since iOS 9 IIRC.

```swift
let indexPath = NSIndexPath(forRow: 0, inSection: 0)
vc.tableView.scrollToRowAtIndexPath(indexPath, atScrollPosition: UITableViewScrollPosition.Bottom, animated: true)
```
