### ISSUE TITLE
Trigger update at an early stage

### ISSUE THREAD

**Issue by mamouneyya** [pronebird/UIScrollView-InfiniteScroll#35]
It would be a nice feature to be able to pre-fetch new content at an early stage, before reaching the exact bottom of the scroll view. Something like providing a configurable distance var (from the bottom) so the library triggers the event when reaching.

**Comment by pronebird** [comment]
Yes I agree! Related PR: https://github.com/pronebird/UIScrollView-InfiniteScroll/pull/7

**Comment by pronebird** [comment]
https://github.com/pronebird/UIScrollView-InfiniteScroll/commit/339bdd0e81fc736c4716ada7fed26e286e4b2dc2 adds block to modify default content offset used to trigger update. Haven't tested it yet.

**Comment by pronebird** [comment]
Released as a part of 0.9.1.
