### ISSUE TITLE
Can't see loader

### ISSUE THREAD

**Issue by NathanVss** [pronebird/UIScrollView-InfiniteScroll#37]
Hello, nice lib.

Here is my code : 
`  
        self.tableView.infiniteScrollIndicatorStyle = .WhiteLarge
        self.tableView.addInfiniteScrollWithHandler { (scrollView) -> Void in

```
        if self.loadingMore {
            print("Currently loading more")
            return
        }
        if self.allLoaded {
            print("All loaded")
            return
        }

        self.paginator.incr()
        self.load()

    }
    load()`
```

The closure is succesfully called, but I can't see any loading animation at the bottom of the screen. Must I implement it my self ? ( If yes, with which component ? )
PS: I use storyboard.

**Comment by pronebird** [comment]
Hi,

When this block is called, infinite scroll indicator should be at the bottom of table view and additional content inset should be added to accommodate indicator view. 

When you finish loading data you have to finish animations, i.e:

```swift
tableView.addInfiniteScrollWithHandler { [weak self] (tableView) -> Void in
            self?.fetchData() {
                tableView.finishInfiniteScroll()
            }
        }
```

to conditionally prevent indicator view from firing the handler block and showing up (i.e. no more data to load), you can implement `shouldShowInfiniteScrollHandler` block, i.e.:

```swift
tableView.setShouldShowInfiniteScrollHandler { [weak self] (tableView) -> Bool in
            return self?.allLoaded == false
        }
```

Apart from that, what platform do you have? If that's tvOS I am afraid that I wasn't able to make it work.

**Comment by pronebird** [comment]
Closing due to no response. Please re-open this issue if you still experience the described problem.
