### ISSUE TITLE
User interaction locked up after finishInfiniteScroll()

### ISSUE THREAD

**Issue by ka05** [pronebird/UIScrollView-InfiniteScroll#40]
When i scroll down and trigger the refresh it shows the spinner but when the spinner disappears the UI is locked up for nearly 4 seconds for me on an IPhone 4s before i can scroll again.

**Comment by pronebird** [comment]
Hi! Do you call `finishInfiniteScroll()` on main thread? That sounds like threading issue to me.

**Comment by pronebird** [comment]
Closing due to no response. Please re-open this issue if you still experience the described problem.
