### ISSUE TITLE
How to change position of  loading indicator?

### ISSUE THREAD

**Issue by mengheangrat** [pronebird/UIScrollView-InfiniteScroll#53]
![simulator screen shot dec 29 2016 10 48 41 am copy](https://cloud.githubusercontent.com/assets/10340553/21536399/28cb3fac-cdb5-11e6-887d-ad87f12fa96e.png)

**Comment by pronebird** [comment]
You can control vertical margin via `infiniteScrollIndicatorMargin`. 

Documentation is available at:

http://pronebird.github.io/UIScrollView-InfiniteScroll/Categories/UIScrollView(InfiniteScroll).html#/c:objc(cs)UIScrollView(py)infiniteScrollIndicatorMargin

**Comment by mengheangrat** [comment]
collectionView?.infiniteScrollIndicatorView = CustomInfiniteIndicator(frame: CGRect(x: 0, y: -70, width: 35, height: 35))
    // Set custom indicator margin
    collectionView!.infiniteScrollIndicatorMargin = 70
    // Add infinite scroll handler
    collectionView!.addInfiniteScroll { [weak self] (scrollView) -> Void in
      self?.fetchDataFresh(){
        scrollView.finishInfiniteScroll()
      }
    }
    collectionView!.infiniteScrollTriggerOffset = 100
    refreshControl.addTarget(self, action: #selector(self.refreshData), for: UIControlEvents.valueChanged)
    self.collectionView!.addSubview(refreshControl)
Still not working

**Comment by pronebird** [comment]
So roughly that's how it should be:

![infinitescrollindicatormargin](https://cloud.githubusercontent.com/assets/704044/21546392/5e60cdfa-cdd6-11e6-8e25-23008031033e.jpg)

Even with refresh control in everything works as expected here testing with iOS 10.2 simulator. Please refer to demo app coming with the library.

**Comment by mengheangrat** [comment]
@pronebird  Now It's worked. 
It's error because of add `infiniteScrollTriggerOffset` after `addInfiniteScroll` <br>

Thank you so much.
