### ISSUE TITLE
Does this deal with any memory management issues?

### ISSUE THREAD

**Issue by russell064** [pronebird/UIScrollView-InfiniteScroll#54]
...like, having **loads** of views inside a scrollview.

Say for example I had 1000 UIImageViews inside a scrollview, would this framework deal with any memory issues like a UITableView would?

**Comment by pronebird** [comment]
Hi,

No it's purely a scroll spy with minimal visual indication when fetching content. If you need to recycle views within scroll view you have to write your own logic just like UITableView or UICollectionView does. But then, why not to use UICollectionView instead?
