### ISSUE TITLE
Объяните плиз)

### ISSUE THREAD

**Issue by SergeyOleynich** [pronebird/UIScrollView-InfiniteScroll#6]
В категории есть метод 
- (void)addInfiniteScrollWithHandler:(void(^)(UIScrollView* scrollView))handler;
Зачем он нужен?что он начинает делать? 
И так же 
- (void)removeInfiniteScroll;
Его необходимо всегда вызывать или только когда используешь первый метод?

**Comment by pronebird** [comment]
- `addInfiniteScrollWithHandler` активирует интерфейс и логику связанную с бесконечным скроллом и устанавливает блок, который вызывается для подгрузки новых данных.
- `removeInfiniteScroll` удаляет бесконечный скрол. Его можно вообще не вызывать, он существует исключительно для случаев с конечным источником данных, когда достигнув конца ленты ты можешь удалить бесконечный скролл.

Проект включает в себя демонстрационное приложение, которое ты можешь скачать из репозитория и запустить вручную или использовать CocoaPod:

```bash
pod try UIScrollView-InfiniteScroll
```

Примеры по использованию были также на главной странице:
https://github.com/pronebird/UIScrollView-InfiniteScroll#basic-usage

**Comment by SergeyOleynich** [comment]
Спасибо за ответ)
А зачем нужен метод с блоком?
- (void)finishInfiniteScrollWithCompletion:(void(^)(UIScrollView* scrollView))handler;

**Comment by pronebird** [comment]
Не за что, блок вызывается по завершению анимации.

Документацию для 0.6.0 поломалась, но для 0.5.2 доступна, там это все описано:

[http://cocoadocs.org/docsets/UIScrollView-InfiniteScroll/0.5.2/Categories/UIScrollView+InfiniteScroll.html#//api/name/finishInfiniteScrollWithCompletion:](http://cocoadocs.org/docsets/UIScrollView-InfiniteScroll/0.5.2/Categories/UIScrollView+InfiniteScroll.html#//api/name/finishInfiniteScrollWithCompletion:)

**Comment by SergeyOleynich** [comment]
И если не сложно то последнее)
Выходит что 
(void)addInfiniteScrollWithHandler:(void(^)(UIScrollView* scrollView))handler 
вызывается сразу как только анимация загрузки становиться в области видимости? А уже 
(void)finishInfiniteScrollWithCompletion:(void(^)(UIScrollView* scrollView))handler 
вызывается после того как я сделал 
finishInfiniteScroll
Только вот пока что не могу представить когда так нужно, если я правильно считаю.

**Comment by pronebird** [comment]
Блок который ты передаешь в `addInfiniteScrollWithHandler` вызывается если нужно подгрузить новые данные в таблицу. Это происходит когда пользовать промотал до самого низа таблицы, в этот момент анимация уже началась.

В вызванном блоке ты вызываешь загрузку своих данных. После того как данные загружены, ты обновляешь таблицу и вызываешь `finishInfiniteScroll` чтобы завершить анимацию вращения.

Посмотри примеры.

**Comment by SergeyOleynich** [comment]
Все вроде понял попробовал в примере поделать разные варианты вроде более менее разобрался)Спасибо)
как я понял то метод 
finishInfiniteScroll
просто завершает анимацию подгрузки, а 
(void)finishInfiniteScrollWithCompletion:(void(^)(UIScrollView* scrollView))handler 
завершает анимацию плюс оповещает нас когда она закончилась чтобы мы могли что-то сделать.
Спасибо за ответы)

**Comment by pronebird** [comment]
Да, разница как и в любом другом API лишь в том, что последний метод с блоком оповещает о завершении анимации. Это может быть полезно, если например, после подгрузки данных ты хочешь промотать в середину таблицы. Соответсвенно чтобы сделать анимацию плавной и избежать конфликтов, в таком случае лучше использовать блок.

**Comment by SergeyOleynich** [comment]
Спасибо)
