### ISSUE TITLE
XCode 'Documentation Issue' warnings

### ISSUE THREAD

**Issue by voltaek** [pronebird/UIScrollView-InfiniteScroll#60]
XCode is showing five warnings inside of `UIScrollView+InfiniteScroll.m`, each of which says "Empty paragraph passed to '@param' command". It seems the documentation on five of the methods in that file declare a parameter and its name, but do not give a description of the parameter.

**Comment by pronebird** [comment]
Good catch! Indeed missing documentation has to be added to suppress such issues.

**Comment by musbaalbaki** [comment]
+1

**Comment by pronebird** [comment]
Fixed in #63
