### ISSUE TITLE
Cannot invoke "finishInfiniteScroll" with no arguments

### ISSUE THREAD

**Issue by keithmichelson** [pronebird/UIScrollView-InfiniteScroll#65]
While converting to swift 3 I'm getting this error:
Cannot invoke "finishInfiniteScroll" with no arguments. I don't see any arguments in the docs.

```
tableView.addInfiniteScroll { (scrollView) -> Void in
            self.fetchData() {
                scrollView.finishInfiniteScroll()
            }
        }
```

Any ideas?

Thanks.

**Comment by pronebird** [comment]
In Objective-C there are two `finishInfiniteScroll`, one takes the completion handler. I need to take a look why that happens in Swift.

**Comment by keithmichelson** [comment]
Thanks for looking at it. I'll keep checking back.

**Comment by pronebird** [comment]
I have no problem with that and just converted demo project to Swift 4.

<img width="901" alt="screenshot 2017-11-23 15 01 14" src="https://user-images.githubusercontent.com/704044/33176534-aa12e594-d05f-11e7-8a37-4c32d3550d72.png">

**Comment by keithmichelson** [comment]
I just converted to swift 4 from 3 now and don't get that anymore. I don't get code completion for that function like you do.

`tableView?.addInfiniteScroll { [weak self] (scrollView) -> Void in
            self?.fetchData() {
                scrollView.finishInfiniteScroll()
            }
        }`

Gets this error but there suggested fix gives another error:
Cannot convert value of type '(_) -> ()' to expected argument type '((Any?) -> Void)!'
Insert ' as! (Any?) -> Void'

It's weird though, it does build even with the error.

**Comment by keithmichelson** [comment]
Figure it out, looks like your code is fine. If I delete the DERIVED DATA folder everything works. No errors and code completion.

https://stackoverflow.com/questions/46504286/xcode-9-autocomplete-not-working-100-partially-working

Thanks for your help.

**Comment by pronebird** [comment]
@keithmichelson alright great! You can use the following shortcut `cmd + shift + K`  to clean up derived data from Xcode without going to Finder.
