### ISSUE TITLE
Infinite scrolling not working on UICollectionView

### ISSUE THREAD

**Issue by reza-khalafi** [pronebird/UIScrollView-InfiniteScroll#67]
Hello 
I used this component for table view and worked correctly. but does not work on collection view. just one time load more works.

**Comment by pronebird** [comment]
Hi,

Thanks for reporting this. I admit that the component needs some maintenance to make sure it works as expected on iOS 11. I haven't touched it since iOS 10 I think.

**Comment by makomori** [comment]
It's working on UICollectionView, iOS 11 for me.

**Comment by pronebird** [comment]
@reza-khalafi could please share the iOS version you run?

**Comment by pronebird** [comment]
@reza-khalafi the fixes for iOS 11 are now in development, see https://github.com/pronebird/UIScrollView-InfiniteScroll/pull/69. 

It would be awesome if you could pull the PR and see if it fixes the broken collection view for you. If not I need more to figure out what exactly does not work.

**Comment by reza-khalafi** [comment]
Thank you

**Comment by pronebird** [comment]
Closing since it seems to me that issue may be related to iOS 11 targets, support for iOS 11 is still WIP though.
