### ISSUE TITLE
Does it work Offline and Online Support?

### ISSUE THREAD

**Issue by TharH** [pronebird/UIScrollView-InfiniteScroll#73]
Firstly, I loaded the  collectionview without internet connection and I turned on the internet. After I turned on the internet, It was show the data that I limit. But I doesn't call the second request. And It was showing indicator and empty screen. Could I get some example ASAP? Thank a lot.

**Comment by pronebird** [comment]
It's a UI component so it makes no assumption about the network status. You should trigger a manual update when appropriate.
