### ISSUE TITLE
Cannot Integrate the library with Swift Package Manager

### ISSUE THREAD

**Issue by Abanoub-Emil** [pronebird/UIScrollView-InfiniteScroll#87]
When adding the library to the project this file 'UIScrollView_InfiniteScroll/UIScrollView+InfiniteScroll.h' is not found.

........./Objc-Bridge-Header.h:16:9: error: 'UIScrollView_InfiniteScroll/UIScrollView+InfiniteScroll.h' file not found
#import <UIScrollView_InfiniteScroll/UIScrollView+InfiniteScroll.h>

1 warning and 1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/username/Library/Developer/Xcode/DerivedData/projectName/Build/Intermediates.noindex/PrecompiledHeaders/Objc-Bridge-Header-swift_3B8HW3B4VST5E-clang_1HSXBDACT2ROO.pch' for bridging header '/Users/project-place/Objc-Bridge-Header.h'

**Comment by pronebird** [comment]
Seems like `Package.swift` needs to be updated. I will have a look soon.

**Comment by pronebird** [comment]
Updated `README.md`. If you use Swift Package Manager (SPM) then you don't need to use bridging header, simply import as any other dependency and `UIScrollView` subclasses should be extended with new methods.

```swift
import UIScrollView_InfiniteScroll
```
