### ISSUE TITLE
Demo's tableView is jumpy/choppy

### ISSUE THREAD

**Issue by waterlee23** [pronebird/UIScrollView-InfiniteScroll#9]
Hi,

This might not be an issue. For the table view demo, when you scroll down loading more cells at the bottom, and then scroll back to top(slowly), you can see the table view is jumpy. 
p.s. I have the same problem with my project but I don't know how to fix it, so I try to search a good demo and find this project :)

**Comment by pronebird** [comment]
UIKit bug related to self-sizing cells, I don't think I can do anything here.

**Comment by waterlee23** [comment]
@pronebird Thanks, I thought it was my fault to introduced this problem
